### ISSUE TITLE
Rent flow

### ISSUE THREAD

**Issue by RosaStamp** [RosaStamp/sprint2#3]
Create the rent flow for renting and tenancy.
Implement on existing flow.
Change  the entry form.

**Comment by georgepatrik** [comment]
![56321830_451205302287257_348827137723072512_n.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c7d1e626dcafe00131e265a/125516c66e82c728ace21e0d46bdc2c971d3dbfadfd6eb16f50fa0c17a1675217153f17e27bab07ce71a29565e5c49ab435b5f43fefc8829c9e82e6c981c49b28b380c30d43703a9ebd31eea09b9208a198dbfbddf4cc2bb6b21e683db1a380c190acbae0361ffc412820db459eb5f54ad193766e372377e43961972246e6e34e6.jpg)
