### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by RosaStamp** [RosaStamp/sprint2#8]
Restart the chat when refreshing the page.

**Comment by nikomiso** [comment]
// TODO: Play with this code to see how we can close a socket

that.socket.addEventListener('close', function(event) {
    console.log('SOCKET CLOSED!');
    that.trigger('disconnected', event);
    if (that.reconnect_count < that.config.max_reconnect) {
      setTimeout(function() {
        console.log('RECONNECTING ATTEMPT ', ++that.reconnect_count);
        that.connectWebsocket(that.config.ws_url);
      }, that.config.reconnect_timeout);
    } else {
      that.message_window.className = 'offline';
    }
  });

**Comment by georgepatrik** [comment]
//TODO: It's about errors on connection with the database and how to restart the connection.

https://stackoverflow.com/questions/20210522/nodejs-mysql-error-connection-lost-the-server-closed-the-connection
